baseURL = 'https://dfir-ahmed.me/' 
languageCode = 'en-us'
title = 'Ahmed Alwedyan | Cybersecurity Portfolio'
theme = 'PaperMod'

[params]
    defaultTheme = "dark"
    displayFullContent = false
    showShareButtons = true
    
    [params.profileMode]
        enabled = true
        title = "Ahmed Alwedyan"
        subtitle = "SOC Analyst | DFIR | CTF Player&Author"
        imageUrl = "https://github.com/Ahmad-Alwedyan.png" 
